# Generated by Django 5.1.2 on 2025-05-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_equipo_comprobante_pago_alter_equipo_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('GRUPO', 'Fase de Grupos'), ('QF', 'Cuartos de Final'), ('SF', 'Semifinal'), ('FI', 'Final'), ('OTRA', 'Otra')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('grupo', models.CharField(blank=True, max_length=1, null=True)),
                ('es_eliminatoria', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(help_text='Orden cronológico de la fase')),
            ],
        ),
        migrations.CreateModel(
            name='Enfrentamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('best_of', models.PositiveIntegerField(default=1)),
                ('completado', models.BooleanField(default=False)),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos_como_local', to='core.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos_como_visitante', to='core.equipo')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfrentamientos_ganados', to='core.equipo')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfrentamientos', to='core.fase')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('link_replay', models.URLField(blank=True, help_text='Enlace a la repetición o video', null=True)),
                ('enfrentamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='core.enfrentamiento')),
                ('equipo_ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='core.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=1)),
                ('victorias', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('partidas_jugadas', models.PositiveIntegerField(default=0)),
                ('oro_total', models.PositiveIntegerField(default=0)),
                ('torres_destruidas', models.PositiveIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipo')),
            ],
            options={
                'unique_together': {('equipo', 'grupo')},
            },
        ),
    ]
