# Generated by Django 5.1.2 on 2025-06-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fase_enfrentamiento_partida_clasificaciongrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfrentamiento',
            name='score_equipo1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enfrentamiento',
            name='score_equipo2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
